---
label: Product
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: image_gallery
  name: images
  label: images
- type: text
  name: description
  label: description
- type: text
  name: price
  label: price
- type: text
  name: discount_price
  label: discount_price
- type: tag_list
  name: colors
  label: colors
- type: tag_list
  name: sizes
  label: sizes
pages:
- exampleSite/content/english/products/corduroy-shirt-regular-fit.md
- exampleSite/content/english/products/cotton-flannel-shirt.md
- exampleSite/content/english/products/easy-iron-shirt-slim-fit.md
- exampleSite/content/english/products/freefit-slim-jeans.md
- exampleSite/content/english/products/oxford-shirt-regular-fit.md
- exampleSite/content/english/products/regular-jeans.md
- exampleSite/content/english/products/slim-jeans.md
- exampleSite/content/english/products/tech-stretch-skinny-jeans.md
